apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  containers:
  - name: kubeturbo
    image: dongyiyang/kubeturbo:dev
    command:
      - /bin/kubeturbo
    args:
      - --v=2
      - --kubeconfig=/etc/kubeturbo/kubeconfig
      - --turboconfig=/etc/kubeturbo/config
      - --testingflag=/etc/kubeturbo/flag
    volumeMounts:
    - name: turboconfig
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: turboconfig
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always
