apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
{{- if eq .Values.roleName "turbo-cluster-reader" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-reader
rules:
  - apiGroups:
      - ""
      - apps
      - app.k8s.io
      - apps.openshift.io
      - batch
      - extensions
      - machine.openshift.io
      - turbonomic.com
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
      - applications
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
      - deploymentconfigs
      - machinesets
      - machines
      - operatorresourcemappings
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
    verbs:
      - get
  - apiGroups:
      - policy.turbonomic.io
    resources:
      - slohorizontalscales
      - policybindings
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- if eq .Values.roleName "turbo-cluster-admin" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-admin
rules:
  - apiGroups:
      - ""
      - batch
    resources:
      - pods
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - apps.openshift.io
      - extensions
      - machine.openshift.io
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deploymentconfigs
      - machinesets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
      - apps
      - batch
      - extensions
      - policy
      - app.k8s.io
      - turbonomic.com
      - machine.openshift.io
    resources:
      - nodes
      - machines
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
      - cronjobs
      - applications
      - operatorresourcemappings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
      - pods/log
    verbs:
      - get
  - apiGroups:
      - policy.turbonomic.io
    resources:
      - slohorizontalscales
      - policybindings
    verbs:
      - get
      - list
      - watch
{{- end }}
---
kind: ClusterRoleBinding
# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBinding }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  # accepted values cluster-reader disc and monitoring.
  name: {{ .Values.roleName }}
  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io