# Default values for kubeturbo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replace the image with desired version
image:
  repository: vmturbo/kubeturbo
  tag: 6.3
  pullPolicy: IfNotPresent

#nameOverride: ""
#fullnameOverride: ""

# Turbo server version and address
serverMeta:
  version: TURBONOMIC_SERVER_VERSION
  turboServer: https://Turbo_server_URL

# Turbo server api user and password
# The opsManagerUserName requires Turbo administrator role
restAPIConfig:
  opsManagerUserName: Turbo_username
  opsManagerPassword: Turbo_password

#targetConfig:
#  targetName: Your_k8s_cluster

args:
  # logging level
  logginglevel: 2
  # If running on k8s 1.10.x or older, set https to false and change port 10255 for kubelet
  kubelethttps: true
  kubeletport: 10250
  # set to false if using IP for stitching
  stitchuuid: true
  # if Kubernetes version is older than 1.6, then add another arg for move/resize action
  pre16k8sVersion: false
