apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  nodeSelector:
    kubeturbo: deployable
  containers:
  - name: kubeturbo
    # The image is the same one as used in non-OpenShift k8s distributions
    image: vmturbo/kubeturbo:6.0
    args:
      - --turboconfig=/etc/kubeturbo/config
      - --kubelet-https=true
      - --kubelet-port=10250
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always
