apiVersion: v1
kind: Pod
metadata:
  name: cpu-load-generator
spec:
  containers:
  - name: cpu-load-generator
    image: dongyiyang/cpu-load-generator:beta
    args:
    - -l
    - "0.2"
    - -c
    - "0"
    resources:
      requests:
        cpu: 250m 
        memory: 100Mi

