apiVersion: v1
kind: ConfigMap
metadata:
  name: turbo-config-{{ .Release.Name }}
data:
  turbo.config: |-
     {
        "communicationConfig": {
            "serverMeta": {
                "version": "{{ .Values.serverMeta.version }}",
                "turboServer": "{{ .Values.serverMeta.turboServer }}"
            },
            "restAPIConfig": {
                "opsManagerUserName": "{{ .Values.restAPIConfig.opsManagerUserName }}",
                "opsManagerPassword": "{{ .Values.restAPIConfig.opsManagerPassword }}"
            }
        {{- if .Values.targetConfig }}
          {{- if .Values.targetConfig.targetName }}
          "targetConfig": {
              "targetName": "{{ .Values.targetConfig.targetName }}"
          }
          {{- end }}
        {{- end }}
        }
     }