apiVersion: v1
kind: Namespace
metadata:
  name: turbo
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubeturbo
  namespace: turbo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubeturbo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: deploy/kubeturbo-racm/deploy
  labels:
    app: kubeturbo
  name: kubeturbo-subscription-0
  namespace: turbo
spec:
  channel: ggithubcom-turbonomic-kubeturbo-ns/ggithubcom-turbonomic-kubeturbo
  overrides:
    - clusterName: openshift-cluster-1
      clusterOverrides:
        - path: spec.packageOverrides
          value:
            - packageName: kubeturbo-release
              packageOverrides:
                - path: spec.serverMeta.turboServer
                  value: 'https://topology-processor-turbonomic.containers.appdomain.cloud'
                - path: spec.targetConfig.targetName
                  value: openshift-cluster-1
    - clusterName: openshift-cluster-2
      clusterOverrides:
        - path: spec.packageOverrides
          value:
            - packageName: kubeturbo-release
              packageOverrides:
                - path: spec.serverMeta.turboServer
                  value: 'https://topology-processor-turbonomic.containers.appdomain.cloud'
                - path: spec.targetConfig.targetName
                  value: openshift-cluster-2
  placement:
    placementRef:
      kind: PlacementRule
      name: kubeturbo-placement-0
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: kubeturbo
  name: kubeturbo-placement-0
  namespace: turbo
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
