apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeturbo-operator
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - nodes
      - pods
      - configmaps
      - endpoints
      - events
      - deployments
      - persistentvolumeclaims
      - replicasets
      - replicationcontrollers
      - services
      - secrets
      - serviceaccounts
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - apps
      - extensions
      - policy
    resources:
      - daemonsets
      - endpoints
      - limitranges
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
      - resourcequotas
      - services
      - statefulsets
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes/spec
      - nodes/stats
  - verbs:
      - '*'
    apiGroups:
      - charts.helm.k8s.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
  - verbs:
      - create
      - get
      - list
      - update
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
