apiVersion: v1
kind: ServiceAccount
metadata:
  name: turbo-user
  annotations:
    "helm.sh/resource-policy": keep
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: turbo-all-binding
  annotations:
    "helm.sh/resource-policy": keep
subjects:
  - kind: ServiceAccount
    name: turbo-user
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io