apiVersion: v1
kind: ServiceAccount
metadata:
  name: turbo-user
---
kind: ClusterRoleBinding
# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: turbo-all-binding
subjects:
  - kind: ServiceAccount
    name: turbo-user
    namespace: {{ .Release.Namespace }}
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  # accepted values cluster-reader disc and monitoring. federation?
  name: cluster-admin
  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io