packageName: kubeturbo-marketplace-certified
channels:
  - name: stable
    currentCSV: kubeturbo-marketplace-operator.v7.22.9
  - name: alpha
    currentCSV: kubeturbo-marketplace-operator.v7.22.6
defaultChannel: stable
