apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 3
  selector:
    name: frontend
    app: fff
  template:
    metadata:
      labels:
        name: frontend
        app: fff
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_containers/example-guestbook-php-redis:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "100Mi"
