apiVersion: v1
kind: Pod
metadata:
  name: nginx-two
spec:
  containers:
  - name: nginx
    image: jonlangemak/docker:web_container_80 
    ports:
    - containerPort: 80
      name: http-server
  - name: nginx-2
    image: jonlangemak/docker:web_container_8080
    ports:
    - containerPort: 8080
      name: http-server-2
