apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-admin
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - extensions
      - policy
    resources:
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - daemonsets
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
    verbs:
      - get