apiVersion: v1
kind: ConfigMap
metadata:
  # use this yaml to create a config that kubeturbo will use to connect to the Turbo Server
  # Provide a value for the config name: and update namespace if needed
  name: turbo-config
  namespace: turbo
data:
  # Update the values for version, turboServer, opsManagerUserName, opsManagerPassword
  # For version, use Turbo Server Version, even when running CWOM
  # The opsManagerUserName requires Turbo administrator role
  # targetConfig is optional. targetName provides custom label in UI
  # Master nodes are by default not uniquely identified. Use masterNodeDetectors to define by node name patterns using regex or node labels.
  # DaemonSets are identified by default. Use daemonPodDetectors to identify by name patterns using regex or by namespace.
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "<Turbo_Server_Version>",
                "turboServer": "https://<Turbo_server_URL>"
            },
            "restAPIConfig": {
                "opsManagerUserName": "<Turbo_username>",
                "opsManagerPassword": "<Turbo_password>"
            }
        },
        "targetConfig": {
            "targetName":"Name_Your_Cluster"
        },
        "masterNodeDetectors": {
           "nodeNamePatterns": [ ".*master.*" ],
           "nodeLabels": [ {"key": "node-role.kubernetes.io/master", "value": ".*"} ]
        }
    }