apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-reader
rules:
  - apiGroups:
      - ""
      - apps
      - app.k8s.io
      - apps.openshift.io
      - batch
      - extensions
      - machine.openshift.io
      - turbonomic.com
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
      - applications
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
      - deploymentconfigs
      - machinesets
      - machines
      - operatorresourcemappings
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
    verbs:
      - get
