apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-admin
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
      - app.k8s.io
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - daemonsets
      - statefulsets
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - extensions
      - policy
    resources:
      - services
      - endpoints
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
      - applications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
    verbs:
      - get
