apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: turbo-cluster-admin
rules:
  - apiGroups:
      - ""
      - batch
    resources:
      - pods
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - apps.openshift.io
      - extensions
      - machine.openshift.io
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deploymentconfigs
      - machinesets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
      - apps
      - batch
      - extensions
      - policy
      - app.k8s.io
      - turbonomic.com
      - machine.openshift.io
    resources:
      - nodes
      - machines
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
      - cronjobs
      - applications
      - operatorresourcemappings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/metrics
      - nodes/proxy
      - pods/log
    verbs:
      - get
