// Code generated by protoc-gen-go.
// source: ActionExecution.proto
// DO NOT EDIT!

/*
Package common_dto is a generated protocol buffer package.

It is generated from these files:
	ActionExecution.proto
	CommonDTO.proto
	Discovery.proto
	MediationMessage.proto
	SupplyChain.proto

It has these top-level messages:
	ActionItemDTO
*/
package sdk

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ActionResponseState int32

const (
	ActionResponseState_PENDING_ACCEPT ActionResponseState = 0
	ActionResponseState_ACCEPTED       ActionResponseState = 1
	ActionResponseState_REJECTED       ActionResponseState = 2
	ActionResponseState_IN_PROGRESS    ActionResponseState = 3
	ActionResponseState_SUCCEEDED      ActionResponseState = 4
	ActionResponseState_FAILED         ActionResponseState = 5
	ActionResponseState_RECOMMENDED    ActionResponseState = 6
	ActionResponseState_DISABLED       ActionResponseState = 7
	ActionResponseState_QUEUED         ActionResponseState = 8
)

var ActionResponseState_name = map[int32]string{
	0: "PENDING_ACCEPT",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "IN_PROGRESS",
	4: "SUCCEEDED",
	5: "FAILED",
	6: "RECOMMENDED",
	7: "DISABLED",
	8: "QUEUED",
}
var ActionResponseState_value = map[string]int32{
	"PENDING_ACCEPT": 0,
	"ACCEPTED":       1,
	"REJECTED":       2,
	"IN_PROGRESS":    3,
	"SUCCEEDED":      4,
	"FAILED":         5,
	"RECOMMENDED":    6,
	"DISABLED":       7,
	"QUEUED":         8,
}

func (x ActionResponseState) Enum() *ActionResponseState {
	p := new(ActionResponseState)
	*p = x
	return p
}
func (x ActionResponseState) String() string {
	return proto.EnumName(ActionResponseState_name, int32(x))
}
func (x *ActionResponseState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionResponseState_value, data, "ActionResponseState")
	if err != nil {
		return err
	}
	*x = ActionResponseState(value)
	return nil
}

type ActionItemDTO_ActionType int32

const (
	ActionItemDTO_NONE                   ActionItemDTO_ActionType = 0
	ActionItemDTO_START                  ActionItemDTO_ActionType = 1
	ActionItemDTO_MOVE                   ActionItemDTO_ActionType = 2
	ActionItemDTO_SUSPEND                ActionItemDTO_ActionType = 3
	ActionItemDTO_TERMINATE              ActionItemDTO_ActionType = 4
	ActionItemDTO_SPAWN                  ActionItemDTO_ActionType = 5
	ActionItemDTO_ADD_PROVIDER           ActionItemDTO_ActionType = 6
	ActionItemDTO_CHANGE                 ActionItemDTO_ActionType = 7
	ActionItemDTO_REMOVE_PROVIDER        ActionItemDTO_ActionType = 8
	ActionItemDTO_PROVISION              ActionItemDTO_ActionType = 9
	ActionItemDTO_RECONFIGURE            ActionItemDTO_ActionType = 10
	ActionItemDTO_RESIZE                 ActionItemDTO_ActionType = 11
	ActionItemDTO_RESIZE_CAPACITY        ActionItemDTO_ActionType = 12
	ActionItemDTO_WARN                   ActionItemDTO_ActionType = 13
	ActionItemDTO_RECONFIGURE_THRESHOLD  ActionItemDTO_ActionType = 14
	ActionItemDTO_DELETE                 ActionItemDTO_ActionType = 15
	ActionItemDTO_RIGHT_SIZE             ActionItemDTO_ActionType = 16
	ActionItemDTO_RESERVE_ON_PM          ActionItemDTO_ActionType = 17
	ActionItemDTO_RESERVE_ON_DS          ActionItemDTO_ActionType = 18
	ActionItemDTO_RESIZE_FOR_EFFICIENCY  ActionItemDTO_ActionType = 19
	ActionItemDTO_RESIZE_FOR_PERFORMANCE ActionItemDTO_ActionType = 20
)

var ActionItemDTO_ActionType_name = map[int32]string{
	0:  "NONE",
	1:  "START",
	2:  "MOVE",
	3:  "SUSPEND",
	4:  "TERMINATE",
	5:  "SPAWN",
	6:  "ADD_PROVIDER",
	7:  "CHANGE",
	8:  "REMOVE_PROVIDER",
	9:  "PROVISION",
	10: "RECONFIGURE",
	11: "RESIZE",
	12: "RESIZE_CAPACITY",
	13: "WARN",
	14: "RECONFIGURE_THRESHOLD",
	15: "DELETE",
	16: "RIGHT_SIZE",
	17: "RESERVE_ON_PM",
	18: "RESERVE_ON_DS",
	19: "RESIZE_FOR_EFFICIENCY",
	20: "RESIZE_FOR_PERFORMANCE",
}
var ActionItemDTO_ActionType_value = map[string]int32{
	"NONE":                   0,
	"START":                  1,
	"MOVE":                   2,
	"SUSPEND":                3,
	"TERMINATE":              4,
	"SPAWN":                  5,
	"ADD_PROVIDER":           6,
	"CHANGE":                 7,
	"REMOVE_PROVIDER":        8,
	"PROVISION":              9,
	"RECONFIGURE":            10,
	"RESIZE":                 11,
	"RESIZE_CAPACITY":        12,
	"WARN":                   13,
	"RECONFIGURE_THRESHOLD":  14,
	"DELETE":                 15,
	"RIGHT_SIZE":             16,
	"RESERVE_ON_PM":          17,
	"RESERVE_ON_DS":          18,
	"RESIZE_FOR_EFFICIENCY":  19,
	"RESIZE_FOR_PERFORMANCE": 20,
}

func (x ActionItemDTO_ActionType) Enum() *ActionItemDTO_ActionType {
	p := new(ActionItemDTO_ActionType)
	*p = x
	return p
}
func (x ActionItemDTO_ActionType) String() string {
	return proto.EnumName(ActionItemDTO_ActionType_name, int32(x))
}
func (x *ActionItemDTO_ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionItemDTO_ActionType_value, data, "ActionItemDTO_ActionType")
	if err != nil {
		return err
	}
	*x = ActionItemDTO_ActionType(value)
	return nil
}

type ActionItemDTO_CommodityAttribute int32

const (
	ActionItemDTO_Capacity    ActionItemDTO_CommodityAttribute = 0
	ActionItemDTO_Limit       ActionItemDTO_CommodityAttribute = 1
	ActionItemDTO_Reservation ActionItemDTO_CommodityAttribute = 2
)

var ActionItemDTO_CommodityAttribute_name = map[int32]string{
	0: "Capacity",
	1: "Limit",
	2: "Reservation",
}
var ActionItemDTO_CommodityAttribute_value = map[string]int32{
	"Capacity":    0,
	"Limit":       1,
	"Reservation": 2,
}

func (x ActionItemDTO_CommodityAttribute) Enum() *ActionItemDTO_CommodityAttribute {
	p := new(ActionItemDTO_CommodityAttribute)
	*p = x
	return p
}
func (x ActionItemDTO_CommodityAttribute) String() string {
	return proto.EnumName(ActionItemDTO_CommodityAttribute_name, int32(x))
}
func (x *ActionItemDTO_CommodityAttribute) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionItemDTO_CommodityAttribute_value, data, "ActionItemDTO_CommodityAttribute")
	if err != nil {
		return err
	}
	*x = ActionItemDTO_CommodityAttribute(value)
	return nil
}

// This message holds values necessary for executing actions on Service Entity discovered with SDK probe
type ActionItemDTO struct {
	// ActionType of the action
	ActionType *ActionItemDTO_ActionType `protobuf:"varint,1,req,name=actionType,enum=common_dto.ActionItemDTO_ActionType" json:"actionType,omitempty"`
	// ActionItem's uuid
	Uuid *string `protobuf:"bytes,2,req,name=uuid" json:"uuid,omitempty"`
	// EntityDTO for the Target ServiceEntity on which the action should be applied
	TargetSE *EntityDTO `protobuf:"bytes,3,req,name=targetSE" json:"targetSE,omitempty"`
	// EntityDTO for the service entity which hosts the targetSE
	HostedBySE *EntityDTO `protobuf:"bytes,4,opt,name=hostedBySE" json:"hostedBySE,omitempty"`
	// EntityDTO for the ServiceEntity by which the Target ServiceEntity is hosted now (for Move action only)
	CurrentSE *EntityDTO `protobuf:"bytes,5,opt,name=currentSE" json:"currentSE,omitempty"`
	// EntityDTO for the ServiceEntity by which the Target ServiceEntity will be hosted
	// after applied the action (for Move action only)
	NewSE *EntityDTO `protobuf:"bytes,6,opt,name=newSE" json:"newSE,omitempty"`
	// CommodityDTO for the commodity on which the action
	// should be applied (current values)
	CurrentComm *CommodityDTO `protobuf:"bytes,7,opt,name=currentComm" json:"currentComm,omitempty"`
	// CommodityDTO for the commodity on which the action
	// should be applied (after the action is applied)
	NewComm *CommodityDTO `protobuf:"bytes,8,opt,name=newComm" json:"newComm,omitempty"`
	// Action Execution Progress
	Progress *int64 `protobuf:"varint,9,opt,name=progress" json:"progress,omitempty"`
	// CommodityAttribute enum notifying type of changed attribute
	CommodityAttribute *ActionItemDTO_CommodityAttribute `protobuf:"varint,10,opt,name=commodityAttribute,enum=common_dto.ActionItemDTO_CommodityAttribute" json:"commodityAttribute,omitempty"`
	// Information for providers of the targetSE.
	Providers        []*ActionItemDTO_ProviderInfo `protobuf:"bytes,11,rep,name=providers" json:"providers,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ActionItemDTO) Reset()         { *m = ActionItemDTO{} }
func (m *ActionItemDTO) String() string { return proto.CompactTextString(m) }
func (*ActionItemDTO) ProtoMessage()    {}

func (m *ActionItemDTO) GetActionType() ActionItemDTO_ActionType {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return ActionItemDTO_NONE
}

func (m *ActionItemDTO) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *ActionItemDTO) GetTargetSE() *EntityDTO {
	if m != nil {
		return m.TargetSE
	}
	return nil
}

func (m *ActionItemDTO) GetHostedBySE() *EntityDTO {
	if m != nil {
		return m.HostedBySE
	}
	return nil
}

func (m *ActionItemDTO) GetCurrentSE() *EntityDTO {
	if m != nil {
		return m.CurrentSE
	}
	return nil
}

func (m *ActionItemDTO) GetNewSE() *EntityDTO {
	if m != nil {
		return m.NewSE
	}
	return nil
}

func (m *ActionItemDTO) GetCurrentComm() *CommodityDTO {
	if m != nil {
		return m.CurrentComm
	}
	return nil
}

func (m *ActionItemDTO) GetNewComm() *CommodityDTO {
	if m != nil {
		return m.NewComm
	}
	return nil
}

func (m *ActionItemDTO) GetProgress() int64 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

func (m *ActionItemDTO) GetCommodityAttribute() ActionItemDTO_CommodityAttribute {
	if m != nil && m.CommodityAttribute != nil {
		return *m.CommodityAttribute
	}
	return ActionItemDTO_Capacity
}

func (m *ActionItemDTO) GetProviders() []*ActionItemDTO_ProviderInfo {
	if m != nil {
		return m.Providers
	}
	return nil
}

// This message holds provider information for the target SE of this ActionItem.
type ActionItemDTO_ProviderInfo struct {
	EntityType       *EntityDTO_EntityType `protobuf:"varint,1,req,name=entityType,enum=common_dto.EntityDTO_EntityType" json:"entityType,omitempty"`
	Ids              []string              `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ActionItemDTO_ProviderInfo) Reset()         { *m = ActionItemDTO_ProviderInfo{} }
func (m *ActionItemDTO_ProviderInfo) String() string { return proto.CompactTextString(m) }
func (*ActionItemDTO_ProviderInfo) ProtoMessage()    {}

func (m *ActionItemDTO_ProviderInfo) GetEntityType() EntityDTO_EntityType {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return EntityDTO_SWITCH
}

func (m *ActionItemDTO_ProviderInfo) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterEnum("common_dto.ActionResponseState", ActionResponseState_name, ActionResponseState_value)
	proto.RegisterEnum("common_dto.ActionItemDTO_ActionType", ActionItemDTO_ActionType_name, ActionItemDTO_ActionType_value)
	proto.RegisterEnum("common_dto.ActionItemDTO_CommodityAttribute", ActionItemDTO_CommodityAttribute_name, ActionItemDTO_CommodityAttribute_value)
}
