apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubeturbo-certified.kubeturbo: ""
  name: kubeturbo-certified
  namespace: turbo
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubeturbo-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
